<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>increase-button</name>
   <tag></tag>
   <elementGuidId>fd795c55-0aaa-41e7-b3e7-0b769f01f21d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.quantity-button.quantity-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-54']/div[2]/form/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;product-54&quot;)/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;cart&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;quantity-nav&quot;]/div[@class=&quot;quantity-button quantity-up&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0807d5f-ad17-4663-9113-6c2138d07ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quantity-button quantity-up</value>
      <webElementGuid>2b145c00-5b23-44c4-9e84-f8ed24b895fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-54&quot;)/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;cart&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;quantity-nav&quot;]/div[@class=&quot;quantity-button quantity-up&quot;]</value>
      <webElementGuid>862ecc02-a4f5-4841-9176-3e8300773479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-54']/div[2]/form/div/div/div</value>
      <webElementGuid>c6285ea1-7026-4484-bc5b-a97a97780f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>a386cf17-3595-4312-9442-e2344f00eb61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
